# Generated by Django 3.2.9 on 2021-12-03 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datacollection',
            name='user',
        ),
    ]
