# Generated by Django 3.2.9 on 2021-12-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_datacollection_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datacollection',
            name='input_query',
        ),
        migrations.RemoveField(
            model_name='datacollection',
            name='updated',
        ),
        migrations.AddField(
            model_name='datacollection',
            name='comment',
            field=models.CharField(default='', max_length=180),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datacollection',
            name='inputText',
            field=models.CharField(default='', max_length=180),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datacollection',
            name='outputText',
            field=models.CharField(default='', max_length=180),
            preserve_default=False,
        ),
    ]
